k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /home/suhorada/.local/state/k9s/screen-dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    #skin: catppuccin-mocha
    #skin: axual
    #skin: black-and-wtf
    #skin: catppuccin-frappe-transparent
    #skin: catppuccin-frappe
    #skin: catppuccin-latte-transparent
    #skin: catppuccin-latte
    #skin: catppuccin-macchiato-transparent
    #skin: catppuccin-macchiato
    #skin: catppuccin-mocha-transparent
    #skin: catppuccin-mocha
    #skin: dracula
    #skin: gruvbox-dark
    #skin: gruvbox-light
    #skin: in-the-navy
    skin: kiss
    #skin: monokai
    #skin: narsingh
    #skin: nightfox
    #skin: nord
    #skin: one-dark
    #skin: red
    #skin: rose-pine
    #skin: snazzy
    #skin: solarized-16
    #skin: solarized-dark
    #skin: solarized-light
    #skin: stock
    # skin: transparent
    enableMouse: false
    headless: false
    logoless: false
    crumbsless: false
    reactive: false
    noIcons: false
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreen: false
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
